name: Python CLI CI/CD

on:
  push:
    branches:
      - sli/sli-version
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Run flake8
      run: |
        poetry run flake8 logs_analyzer
        
    - name: Run ruff
      uses: astral-sh/ruff-action@v3

    - name: Run isort
      run: |
        poetry run isort logs_analyzer

    - name: Run pylint
      run: |
        poetry run pylint logs_analyzer

    - name: Pytest
      run: |
        poetry run pytest .
